# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - opencv-flask

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b18db6b574dd430bb69fff1beb997cfe }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2a9b644c86064dc3873f769a26c291aa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b18db6b574dd430bb69fff1beb997cfe }}/emmanuelallan/opencv-flask:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'opencv-flask'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1b18c3b5474443c68eac25f4179d06d6 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b18db6b574dd430bb69fff1beb997cfe }}/emmanuelallan/opencv-flask:${{ github.sha }}'